disabled_rules:
  - trailing_comma
  - identifier_name
  - void_return
  - operator_whitespace
  - nesting
  - cyclomatic_complexity

line_length:
  warning: 80
  error: 100
  ignores_comments: true

function_body_length:
  - 50

included:
  - CloudyCider
  - CloudyCiderTests
  - CloudyCiderUITests
