trigger:
  - master

jobs:
  - job: lint
    pool:
      vmImage: "macos-latest"
    steps:
      - bash: ./lint.sh

  - job: test
    pool:
      vmImage: "macos-latest"
    steps:
      - bash: ./test.sh
